---
- hosts: web 
  tasks:
    - name: install apache web server
      ansible.builtin.dnf:
        name: httpd
        state: latest
        update_cache: yes 

    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes


    - name: copy the custom website into web server
      ansible.builtin.copy:
        src: /root/playbook/index.html
        dest: /var/www/html
